-- Talengineer V13.0 PostgreSQL Schema for Supabase

-- 1. Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT,
    role TEXT NOT NULL,
    name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Talents Table
CREATE TABLE talents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT,
    skills TEXT,
    region TEXT,
    rate TEXT,
    pricing_model TEXT,
    level TEXT,
    verified_score INTEGER DEFAULT 0,
    bio TEXT,
    contact TEXT UNIQUE,
    stripe_account_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Demands (Projects) Table
CREATE TABLE demands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title TEXT,
    role_required TEXT,
    region TEXT,
    project_type TEXT,
    location TEXT,
    budget TEXT,
    description TEXT,
    contact TEXT,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Project Milestones Table
CREATE TABLE project_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT REFERENCES demands(id) ON DELETE CASCADE,
    phase_name TEXT,
    percentage REAL,
    amount REAL,
    status TEXT DEFAULT 'locked',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Financial Ledgers Table
CREATE TABLE financial_ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT REFERENCES demands(id) ON DELETE CASCADE,
    employer_email TEXT,
    engineer_email TEXT,
    hourly_rate REAL,
    hours_worked REAL,
    total_amount REAL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Project Messages (Babel War Room)
CREATE TABLE project_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id TEXT,
    sender_role TEXT,
    sender_name TEXT,
    original_text TEXT,
    translated_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
