// ── /rates 页九语 UI 字典（lib/i18n 架构 B 试点页）───────────────────────
//
// 【模块风格 —— 全体 lib/i18n 字典模块统一遵守，后续批次照抄本文件】
// - CommonJS 纯数据模块：文件尾 `module.exports = { DICT };`，零依赖，
//   禁止 import React / next 任何东西。理由与 lib/navConfig.js 先例相同：
//   tests/i18nParity.test.js 用 node --test 直接 require 做完整性断言，CJS 零配置；
//   页面侧 Next 的 webpack 对 CJS 互操作正常，
//   `import { DICT } from '../lib/i18n/rates'` 照常可用。
// - 只能放 lib/i18n/ 下，绝不能放 pages/ 内 —— Next 会把 pages/ 下的 .js 当路由。
//
// 【迁移配方 —— 把一个页面的内联九语 DICT 抽到这里的固定五步】
// 1. 把页面内联的 `const DICT = { en:{...}, zh:{...}, ... }` 整块逐字节原样搬进
//    lib/i18n/<页面名>.js（这是"搬移"不是"重写"：文案、数字、链接、来源注释
//    一个字节都不许变——费率/培训/TalScore 等数字的中文来源注释必须原样带过，
//    数字纪律的单一来源在 src/config/fees.js 等处，字典搬家不碰数）。
// 2. 文件尾加 `module.exports = { DICT };`（本文件即样板）。
// 3. 页面删除内联 DICT，改为 `import { DICT } from '../lib/i18n/<页面名>'`
//    （层级更深的页面注意 ../ 的数量）；渲染逻辑一行不动，取值保持
//    `const d = DICT[lang] || DICT.en` 惯用式（useLang 是客户端 hook，
//    SSR 首帧必须仍是合法英文，因此 en 兜底不可省）。
// 4. 在 tests/i18nParity.test.js 的 REQUIRED_LANGS 清单里追加一行
//    `<页面名>: ALL_LANGS`（或该页实际应有的语言列表）——忘了追加测试会红灯。
// 5. `npm test` + `npx next build` 全绿后才算迁完。
const DICT = {
  en: { heroBadge: 'Live Market Data', heroTitle: 'Automation Engineer Rate Benchmarks', heroSub: 'Real-time market rates for industrial automation talent by region. Data sourced from active engineer profiles on Talengineer.', filterLabel: 'Filter by skill:', allSkills: 'All Skills', medianRate: 'Median Rate', noData: 'No rate data available yet.', aboutTitle: 'About This Data', aboutBody1: 'Rates are self-reported by engineers on the Talengineer platform and updated in real time. Figures represent hourly rates in USD.', aboutBody2: 'Industrial specialties tracked: PLC programming, SCADA/HMI development, robotics (Fanuc, KUKA, ABB), electrical panel design, Siemens TIA Portal, Rockwell Studio 5000, process control, and more.', browseBtn: 'Browse Available Engineers →', ctaTitle: 'Need to hire an automation engineer?', ctaBody: 'Post your project and get matched with pre-screened engineers. Escrow payment protects both parties.', ctaBtn: 'Post a Project', calcCta: 'Estimate your project cost with the calculator →', bySpecLabel: 'Browse by specialty:', guidesLabel: 'Regional hiring guides:' },
  zh: { heroBadge: '实时市场数据', heroTitle: '自动化工程师费率基准', heroSub: '按地区实时展示工业自动化人才的市场费率，数据来源于 Talengineer 平台的工程师档案。', filterLabel: '按技能筛选：', allSkills: '全部技能', medianRate: '中位费率', noData: '暂无费率数据。', aboutTitle: '关于本数据', aboutBody1: '费率由工程师在 Talengineer 平台自主填报，实时更新，单位为美元/小时。', aboutBody2: '涵盖专业领域：PLC 编程、SCADA/HMI 开发、机器人（Fanuc/KUKA/ABB）、电气面板设计、西门子 TIA Portal、Rockwell Studio 5000、过程控制等。', browseBtn: '浏览在线工程师 →', ctaTitle: '需要招募自动化工程师？', ctaBody: '发布项目，与经过预审的工程师精准匹配。里程碑托管保障双方权益。', ctaBtn: '发布项目', calcCta: '用成本计算器估算项目预算 →', bySpecLabel: '按方向浏览：', guidesLabel: '分国用人指南：' },
  es: { heroBadge: 'Datos en Tiempo Real', heroTitle: 'Tarifas de Ingenieros de Automatización', heroSub: 'Tarifas de mercado en tiempo real para automatización industrial por región.', filterLabel: 'Filtrar por habilidad:', allSkills: 'Todas las Habilidades', medianRate: 'Tarifa Mediana', noData: 'Sin datos de tarifas disponibles.', aboutTitle: 'Sobre estos datos', aboutBody1: 'Las tarifas son reportadas por los ingenieros y se actualizan en tiempo real en USD/hora.', aboutBody2: 'Especialidades: programación PLC, SCADA/HMI, robótica (Fanuc, KUKA, ABB), diseño de tableros eléctricos, Siemens TIA Portal, Rockwell Studio 5000 y más.', browseBtn: 'Ver Ingenieros Disponibles →', ctaTitle: '¿Necesita contratar un ingeniero?', ctaBody: 'Publique su proyecto y conéctese con ingenieros preseleccionados.', ctaBtn: 'Publicar Proyecto', calcCta: 'Calcule el costo de su proyecto con la calculadora →', bySpecLabel: 'Explorar por especialidad:', guidesLabel: 'Guías de contratación por país:' },
  vi: { heroBadge: 'Dữ liệu thời gian thực', heroTitle: 'Chuẩn mức giá Kỹ sư Tự động hóa', heroSub: 'Mức giá thị trường thời gian thực cho nhân tài tự động hóa công nghiệp theo khu vực.', filterLabel: 'Lọc theo kỹ năng:', allSkills: 'Tất cả kỹ năng', medianRate: 'Giá trung vị', noData: 'Chưa có dữ liệu giá.', aboutTitle: 'Về dữ liệu này', aboutBody1: 'Mức giá do kỹ sư tự báo cáo trên nền tảng và cập nhật theo thời gian thực (USD/giờ).', aboutBody2: 'Lĩnh vực: lập trình PLC, SCADA/HMI, robot (Fanuc/KUKA/ABB), Siemens TIA Portal, Rockwell Studio 5000 và nhiều hơn nữa.', browseBtn: 'Xem Kỹ sư có sẵn →', ctaTitle: 'Cần tuyển kỹ sư tự động hóa?', ctaBody: 'Đăng dự án và được ghép với kỹ sư đã được sàng lọc.', ctaBtn: 'Đăng Dự Án', calcCta: 'Ước tính chi phí dự án bằng máy tính →', bySpecLabel: 'Duyệt theo chuyên môn:', guidesLabel: 'Cẩm nang tuyển dụng theo quốc gia:' },
  hi: { heroBadge: 'लाइव बाज़ार डेटा', heroTitle: 'ऑटोमेशन इंजीनियर दर बेंचमार्क', heroSub: 'क्षेत्र के अनुसार औद्योगिक ऑटोमेशन प्रतिभा के लिए रियल-टाइम बाज़ार दरें।', filterLabel: 'कौशल द्वारा फ़िल्टर करें:', allSkills: 'सभी कौशल', medianRate: 'मध्यिका दर', noData: 'अभी कोई दर डेटा उपलब्ध नहीं है।', aboutTitle: 'इस डेटा के बारे में', aboutBody1: 'दरें इंजीनियरों द्वारा स्व-रिपोर्ट की गई हैं और USD/घंटे में रियल-टाइम अपडेट होती हैं।', aboutBody2: 'विशेषताएं: PLC प्रोग्रामिंग, SCADA/HMI, रोबोटिक्स, Siemens TIA Portal, Rockwell Studio 5000 आदि।', browseBtn: 'उपलब्ध इंजीनियर देखें →', ctaTitle: 'ऑटोमेशन इंजीनियर की ज़रूरत है?', ctaBody: 'अपना प्रोजेक्ट पोस्ट करें और प्री-स्क्रीन्ड इंजीनियरों से मैच करें।', ctaBtn: 'प्रोजेक्ट पोस्ट करें', calcCta: 'कैलकुलेटर से अपने प्रोजेक्ट की लागत का अनुमान लगाएं →', bySpecLabel: 'विशेषज्ञता के अनुसार देखें:', guidesLabel: 'देश-वार नियुक्ति गाइड:' },
  fr: { heroBadge: 'Données en temps réel', heroTitle: 'Tarifs des Ingénieurs en Automatisation', heroSub: 'Tarifs du marché en temps réel pour les talents en automatisation industrielle par région.', filterLabel: 'Filtrer par compétence :', allSkills: 'Toutes les compétences', medianRate: 'Tarif médian', noData: 'Aucune donnée tarifaire disponible pour le moment.', aboutTitle: 'À propos de ces données', aboutBody1: 'Les tarifs sont auto-déclarés par les ingénieurs sur la plateforme et mis à jour en temps réel (USD/heure).', aboutBody2: 'Spécialités : programmation PLC, SCADA/HMI, robotique (Fanuc, KUKA, ABB), Siemens TIA Portal, Rockwell Studio 5000 et plus.', browseBtn: 'Voir les ingénieurs disponibles →', ctaTitle: 'Besoin d\'engager un ingénieur ?', ctaBody: 'Publiez votre projet et soyez mis en relation avec des ingénieurs présélectionnés.', ctaBtn: 'Publier un projet', calcCta: 'Estimez le coût de votre projet avec le calculateur →', bySpecLabel: 'Parcourir par spécialité :', guidesLabel: 'Guides de recrutement par pays :' },
  de: { heroBadge: 'Live-Marktdaten', heroTitle: 'Stundensatz-Benchmarks für Automatisierungsingenieure', heroSub: 'Echtzeit-Marktpreise für Automatisierungstalente nach Region.', filterLabel: 'Nach Fähigkeit filtern:', allSkills: 'Alle Fähigkeiten', medianRate: 'Mediansatz', noData: 'Noch keine Tarifdaten vorhanden.', aboutTitle: 'Über diese Daten', aboutBody1: 'Tarifsätze werden von Ingenieuren auf der Plattform selbst angegeben und in Echtzeit aktualisiert (USD/Stunde).', aboutBody2: 'Spezialgebiete: PLC-Programmierung, SCADA/HMI, Robotik (Fanuc, KUKA, ABB), Siemens TIA Portal, Rockwell Studio 5000 und mehr.', browseBtn: 'Verfügbare Ingenieure ansehen →', ctaTitle: 'Suchen Sie einen Automatisierungsingenieur?', ctaBody: 'Veröffentlichen Sie Ihr Projekt und werden Sie mit vorausgewählten Ingenieuren zusammengebracht.', ctaBtn: 'Projekt veröffentlichen', calcCta: 'Projektkosten mit dem Rechner schätzen →', bySpecLabel: 'Nach Fachgebiet durchsuchen:', guidesLabel: 'Regionale Einstellungsleitfäden:' },
  ja: { heroBadge: 'リアルタイム市場データ', heroTitle: 'オートメーションエンジニア レートベンチマーク', heroSub: '地域別の産業オートメーション人材のリアルタイム市場レート。', filterLabel: 'スキルで絞り込み：', allSkills: '全スキル', medianRate: '中央値レート', noData: 'レートデータはまだありません。', aboutTitle: 'データについて', aboutBody1: 'レートはプラットフォーム上のエンジニアによる自己申告で、リアルタイム更新されます（USD/時間）。', aboutBody2: '対応分野：PLC プログラミング、SCADA/HMI、ロボット（Fanuc/KUKA/ABB）、Siemens TIA Portal、Rockwell Studio 5000 など。', browseBtn: '利用可能なエンジニアを見る →', ctaTitle: 'オートメーションエンジニアが必要ですか？', ctaBody: 'プロジェクトを投稿して、事前審査済みエンジニアとマッチングしましょう。', ctaBtn: 'プロジェクトを投稿', calcCta: 'コスト計算ツールでプロジェクト費用を見積もる →', bySpecLabel: '専門分野で探す：', guidesLabel: '国別採用ガイド：' },
  ko: { heroBadge: '실시간 시장 데이터', heroTitle: '자동화 엔지니어 요율 벤치마크', heroSub: '지역별 산업 자동화 인재의 실시간 시장 요율.', filterLabel: '기술로 필터링:', allSkills: '모든 기술', medianRate: '중앙값 요율', noData: '요율 데이터가 아직 없습니다.', aboutTitle: '데이터 안내', aboutBody1: '요율은 엔지니어가 플랫폼에서 자체 신고하며 실시간으로 업데이트됩니다(USD/시간).', aboutBody2: '전문 분야: PLC 프로그래밍, SCADA/HMI, 로봇(Fanuc/KUKA/ABB), Siemens TIA Portal, Rockwell Studio 5000 등.', browseBtn: '엔지니어 보기 →', ctaTitle: '자동화 엔지니어가 필요하신가요?', ctaBody: '프로젝트를 게시하고 사전 심사된 엔지니어와 매칭되세요.', ctaBtn: '프로젝트 게시', calcCta: '계산기로 프로젝트 비용 추정하기 →', bySpecLabel: '전문 분야별 보기:', guidesLabel: '국가별 채용 가이드:' },
};

module.exports = { DICT };
